//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "coupon_redemptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "coupon_ip")]
    pub coupon_id: Uuid,
    #[sea_orm(unique_key = "coupon_user")]
    pub user_id: Uuid,
    pub redeemed_at: DateTime,
    pub amount_added: Decimal,
    #[sea_orm(unique_key = "coupon_ip")]
    pub ip_address: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::coupons::Entity",
        from = "Column::CouponId",
        to = "super::coupons::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Coupons,
    #[sea_orm(
        belongs_to = "super::user_session::Entity",
        from = "Column::UserId",
        to = "super::user_session::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserSession,
}

impl Related<super::coupons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Coupons.def()
    }
}

impl Related<super::user_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
