//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "coupons")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub code: String,
    pub balance_amount: Decimal,
    pub max_uses: i32,
    pub used_count: i32,
    pub is_active: bool,
    pub expires_at: Option<DateTime>,
    pub created_at: DateTime,
    pub created_by: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::coupon_redemptions::Entity")]
    CouponRedemptions,
}

impl Related<super::coupon_redemptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CouponRedemptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
