//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::chat_message::Entity as ChatMessage;
pub use super::coupon_redemptions::Entity as CouponRedemptions;
pub use super::coupons::Entity as Coupons;
pub use super::proxy_server::Entity as ProxyServer;
pub use super::rental::Entity as Rental;
pub use super::top_ups::Entity as TopUps;
pub use super::user_session::Entity as UserSession;
