//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "proxy_server")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub country: String,
    pub codename: String,
    pub controller_key: String,
    pub price: Decimal,
    pub speed: i32,
    pub slots_available: i32,
    pub proxies_rented: i32,
    pub port: i32,
    pub is_promo: bool,
    pub is_ready: bool,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
